config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post "login_user" => "home#login_user"
  get "sign_out" => "home#sign_out"
  get "download" => "home#download"
  get "calls" => "home#calls"
  namespace :admin do
    resources :users, :except => [:show] do
      collection do
        get :download
      end
    end
    root :to => "admin#index"    
  end
   namespace :api, defaults: {format: 'json'} do
    scope module: :v1 do
      resources :services do
        collection do
          post :access
          get :get_work_schedules
        end
      end
    end
  end
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/services.rb
class Services
  def initialize(session)
    @session = session
  end
  def get_work_schedules()
    data_params = {}
    data_header = {'d-access-token' => @session[:current_user]["token_access"], "Content-Type" => "application/json"}
    data_response = call_services('api/services/get_work_schedules',data_params,data_header,'get')
  end
  def autenticate_user(params)
	  data_params = {'email' => params[:email], 'password': params[:password]}
    data_response = call_services('api/services/access',data_params)
  end
  def call_services(url,data_params,data_header={"Content-Type" => "application/json"},call_method='post')
    p "----------------#{url.inspect}"
  	auth_app = RestClient::Request.execute(method: call_method,
                            url: 'https://runa-app.herokuapp.com/'+url,
                            payload: data_params,
                            headers: data_header
                           )
  	JSON.parse(auth_app.body.as_json)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  default_scope { order('id') } 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :work_schedules
  accepts_nested_attributes_for :work_schedules, reject_if: :all_blank, allow_destroy: true
  def self.validate_access(params)
    admin = self.find_by_email(params[:email])
    if (admin && admin.valid_password?(params[:password]) && admin.admin == false) 
      admin.get_token_user
      r_a = admin
    else
      r_a = false
    end
    r_a
  end

  def get_token_user
    unless self.token_access
      self.token_access = SecureRandom.hex
      self.save
    end
    self.token_access
  end
end

app/models/work_schedule.rb
class WorkSchedule < ApplicationRecord
  belongs_to :user
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < AdminController
	def index
	  users = User.all
	  @admins = users.where(admin: true)
	  @users = users.where(admin: false)
	end
end

app/controllers/admin/user_controller.rb
class Admin::UsersController < AdminController
  require "csv"
  def index
  	@users = User.all
  end
  def new
  	@user = User.new
  end
  def create
    @user = User.new(user_params)
    @user.password = SecureRandom.urlsafe_base64
    if @user.save
      flash[:notice] = 'Usuario Creado'
      redirect_to :controller => "users" and return
    else
      flash[:notice] = 'Error Usuario'
      render action: "new" 
    end
  end
  def edit
  	@user = User.find params[:id]
  end 
   def update
  	@user = User.find(params[:id])

    if params[:user][:password].blank?
      params[:user].delete(:password)
    end
    if @user.update(user_params)
      flash[:notice] = 'Usuario Modificado'
      redirect_to :controller => "users" and return
    else
      flash[:notice] = 'Error Usuario'
      render action: "edit" 
    end
  end
  def download 
    body = ['Nombre','Correo','Administrador','Telefono','Entradas']
    body = body.to_csv
    User.all.each do |user|
      row = [user.name, user.email,user.admin ? 'Administrador' : 'Usuario',user.phone,user.work_schedules.map { |u| "(#{u.schedule.strftime("%d/%m/%Y")}-#{u.start_time.strftime("%H:%M:%S")}-#{u.end_time.strftime("%H:%M:%S")})" }.join(",")]
      body << row.to_csv
    end
    send_data body, filename: 'usuarios.csv'
  end

  def destroy
  	raise params.inspect
    @course.destroy
    flash[:notice] = 'Course Deleted'
    redirect_to :controller => "users" and return
  end
  private

    def user_params
      params.require(:user).permit(:name, :email, :phone, :admin, :password,
       				 work_schedules_attributes: [:id, :schedule, :start_time, :end_time, :_destroy])
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :authenticate_user!
	before_action :validate_admin
    layout 'admin'
	private
	def validate_admin
	  if !current_user.admin?
	  	sign_out(current_user)
	    redirect_to root_path 
	  end
	end
end

app/controllers/api/v1/services_controller.rb
module Api
  module V1
    class ServicesController < ActionController::Base
      respond_to :json
      def access
        @admin = User.validate_access(params)
        if @admin
          render json: @admin
        else
          render json: {error: "No fue posible autenticarte", status: :unprocessable_entity}
        end
      end
      def get_work_schedules
        admin = User.find_by_token_access(request.headers['d-access-token'])
        if admin
          render json: admin.work_schedules
        else
          render json: {error: "No fue posible autenticarte", status: :unprocessable_entity}
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  private
  def after_sign_in_path_for(resource)
    if resource.admin?
      admin_root_url
    else
      root_url
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	require "csv"
	before_action :load_info, only: [:login_user, :index, :download]
	def login_user
	  admin = @services.autenticate_user(params)
	  @error = "Error al registrarse"
	  unless admin["status"] == "unprocessable_entity"
	  	session[:current_user] = admin
	  	redirect_to root_url and return
	  end
	end
	def sign_out
		session[:current_user] = nil
	  	redirect_to root_url and return
	end
	def download
	  	@ws = @services.get_work_schedules

	    body = [session[:current_user]["name"],session[:current_user]["email"],session[:current_user]["phone"]]
	    body = body.to_csv
	    body << ['Fecha','Hora de Entrada','Hora de salida'].to_csv
	    @ws.each do |ws|
	      row = [ws["schedule"].to_date.strftime("%d/%m/%Y"),ws["start_time"].to_time.strftime("%H:%M:%S"),ws["end_time"].to_time.strftime("%H:%M:%S")]
	      body << row.to_csv
	    end
	    send_data body, filename: "#{session[:current_user]["name"]}.csv"
	end
	def index
 	  @ws = session[:current_user].nil? ? [] : @services.get_work_schedules
	end
    private
    def load_info
      @services = Services.new(session)
    end
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/user_helper.rb
module Admin::UserHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/admin/index.html.haml
.col-4.m-4
  .card{:style => "width: 18rem;"}
    .card-body
      %h2 Usuarios
      %p.card-text=@users.count
.col-4.m-4
  .card{:style => "width: 18rem;"}
    .card-body
      %h2 Administradores
      %p.card-text=@admins.count

app/views/admin/users/_form.html.haml
= form_for([:admin, @user], role: 'form') do |f|
  .row
    .col-6
      .form-group
        %label.control-label Nombre
        =f.text_field :name, class: "form-control ", :required=>true
      .form-group
        %label.control-label Correo
        =f.text_field :email, class: "form-control ", :required=>true
      .form-group
        %label.control-label Telefono
        =f.text_field :phone, class: "form-control "
      .form-group
        %label.control-label Contraseña
        -unless @user.new_record?
          =f.password_field :password, class: "form-control "
          %small.text-muted Ingresar si requiere cambiar 
        -else
          =f.password_field :password, class: "form-control ", :required=>true
      .form-group
        %label.control-label Admin
        = f.check_box :admin
    .col-6
      %h3 Entradas
      #schedules
        = f.fields_for :work_schedules do |ws|
          = render 'work_schedule_fields', f: ws
        .links
          = link_to_add_association 'Agregar Entrada', f, :work_schedules
    .col-12
      = f.submit 'Guardar', :class=>"btn btn-primary"
      = link_to 'Regresar', admin_users_path, :class=>"btn btn-info"

app/views/admin/users/_work_schedule_fields.html.haml
.nested-fields
  .row
    .col-4
      .field
        = f.label :Dia
        %br
        =f.text_field :schedule, class: "form-control", placeholder: "Fecha", 'data-provide'=>"datepicker", 'data-date-format'=>"dd/mm/yyyy",:required => true, :value=>"#{f.object.schedule.strftime("%d/%m/%Y") if f.object.schedule}"
    .col-3
      .field
        = f.label :Entrada
        %br
        = f.text_field :start_time, class: "form-control timepicker", :id=>"start_time",:required => true, :value=>"#{f.object.start_time.strftime("%H:%M:%S") if f.object.start_time}"
    .col-3
      .field
        = f.label :Salida
        %br
        = f.text_field :end_time, class: "form-control timepicker",:required => true, :value=>"#{f.object.end_time.strftime("%H:%M:%S") if f.object.end_time}"
    .col-2
      = link_to_remove_association "-", f, :class=>'btn btn-danger'
:javascript
  $('.timepicker').timepicker()

app/views/admin/users/edit.html.haml
.card.mt-3.col-12
  .card-header
    %h2 Edición
  .card-body
    %p.card-text 
      = render 'form'

app/views/admin/users/index.html.haml
.card.mt-3
  .card-header
    %h2 
      Usuarios
      \(
      =@users.count
      \)
  .card-body
    %p.card-text 
      %table.table.table-hover
        %thead
          %tr
            %th{:scope => "col"} #
            %th{:scope => "col"} Nombre
            %th{:scope => "col"} Correo
            %th{:scope => "col"} Telefono
            %th{:scope => "col"} Tipo
            %th{:scope => "col"} Entradas
            %th
              =link_to 'Nuevo',new_admin_user_path,:class=>"btn btn-primary"
              =link_to 'Descargar',download_admin_users_path,:class=>"btn btn-success"
        %tbody
          -@users.each do |user|
            %tr
              %th{:scope => "row"}=user.id
              %td=user.name
              %td=user.email
              %td=user.phone
              %td="#{user.admin? ? 'Admin' : 'Usuario'}"
              %td=user.work_schedules.count
              %td
                =link_to 'Editar',edit_admin_user_path(user),:class=>"btn btn-info"
                = link_to 'Borrar', admin_user_path(user), :method => :delete, :data => { :confirm => '¿Estas seguro?' }, :class=>"btn btn-danger"

app/views/admin/users/new.html.haml
.card.mt-3.col-12
  .card-header
    %h2 Nuevo
  .card-body
    %p.card-text 
      = render 'form'

app/views/home/calls.html.haml
.row.mt-5
  .col-6
    .card
      .card-header
        %h3 Ingreso de usuario
      .card-body
        %p.card-text 
          %table.table
            %tbody
              %tr
                %td Ruta
                %td https://runa-app.herokuapp.com/api/services/access
              %tr
                %td Parametros
                %td="{'email' => <CORREO DE USUARIO>, 'password': <CONTRASEÑA USUARIO>}"
              %tr
                %td Cabeceras
                %td='{"Content-Type" => "application/json"}'
              %tr
                %td Respuesta
                %td='{"id": <ID USUARIO>,"email": <CORREO DE USUARIO>,"name": <NOMBRE DE USUARIO>,"phone": <TELEFONO DE USUARIO>,"token_access": <TOKEN UNICO DE USUARIO>}'
  .col-6
    .card
      .card-header
        %h3 Obtener entradas de horario
      .card-body
        %p.card-text
          %table.table
            %tbody
              %tr
                %td Ruta
                %td https://runa-app.herokuapp.com/api/services/get_work_schedules
              %tr
                %td Parametros
                %td {}
              %tr
                %td Cabeceras
                %td='{"d-access-token" => <TOKEN UNICO DE USUARIO>, "Content-Type" => "application/json"}'
              %tr
                %td Respuesta
                %td='[{"id": <ID HORARIO>,"start_time": <HORARIO ENTRADA>,"end_time": <HORARIO SALIDA>,"schedule":<FECHA DEL REGISTRO>},{"id": <ID HORARIO>,"start_time": <HORARIO ENTRADA>,"end_time": <HORARIO SALIDA>,"schedule":<FECHA DEL REGISTRO>}]'

app/views/home/index.html.haml
-if session[:current_user]
  .card.text-center.mt-5
    .card-header
      %h2 Información para el usuario
      %h4.text-info=session[:current_user]["name"]
      %p.card-text
        %small.text-muted
          \(
          =session[:current_user]["email"]
          =" - #{session[:current_user]["phone"]}" if session[:current_user]["phone"] != ''
          \)
        
    .card-body
      =link_to "Descargar", download_path, :class=>"btn btn-info"
      =link_to "Salir", sign_out_path, :class=>"btn btn-danger"
      %table.table.table-hover.mt-2
        %thead
          %tr
            %th{:scope => "col"} #
            %th{:scope => "col"} Fecha
            %th{:scope => "col"} Hora de entrada
            %th{:scope => "col"} Hora de salida
        %tbody
          -@ws.each do |ws|
            %tr
              %th{:scope => "row"}=ws["id"]
              %td=ws["schedule"].to_date.strftime("%d/%m/%Y")
              %td=ws["start_time"].to_time.strftime("%H:%M:%S")
              %td=ws["end_time"].to_time.strftime("%H:%M:%S")

    .card-footer.text-muted
      Prueba con llamadas

-else
  .col-4.mt-5
    =form_tag(login_user_path, method: "post",:class=>"form-signin",remote: true) do
      .form-label-group
        %label{:for => "inputEmail"} Correo
        =text_field_tag :email,'', autofocus: true, autocomplete: "email", :class=>"form-control", :placeholder=>"Email address", :required=>true
      .form-label-group
        %label{:for => "inputPassword"} Contraseña
        =password_field_tag :password,'', autocomplete: "off", :class=>"form-control", :placeholder=>"Password", :required=>true
      .mt-2
        Visitar 
        =link_to 'API', calls_path
      %button.btn.btn-lg.btn-primary.btn-block.mt-2{:type => "submit"} Entrar

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Runa - Admin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.standalone.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
  	  <%if current_user%>
  		<nav class="navbar navbar-expand-lg navbar-light bg-light">
		  <a class="navbar-brand" href="/admin">RUNA - Admin</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse " id="navbarNav">
		    <ul class="navbar-nav">
		      <%if current_user.admin?%>
		        <li class="nav-item">
		          <%= link_to('Usuarios', admin_users_path, :class=>"nav-link")%>
		        </li>
		      <%end%>
		      <li class="nav-item">
		        <%= link_to('Salir', destroy_user_session_path, method: :delete, :class=>"nav-link")%>
		      </li>
		    </ul>
		  </div>
		</nav>
	  <%end%>
  	  <div class="row justify-content-md-center">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Runa</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
  	  <div class="row justify-content-md-center">
        <%= yield %>
      </div>
    </div>
  </body>
</html>